name: Check Setup

# This is a composite action that checks the setup of the project.

# Inputs
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '16'
  pnpm-version:
    description: 'pnpm version to use'
    required: true
    default: '7.0.0'

# Steps
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      run: npm install -g pnpm@${{ inputs.pnpm-version }}

    - name: Verify pnpm installation
      run: pnpm --version