name: Lint

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check setup
        uses: ./.github/actions/check-setup

      - name: Build the app
        run: pnpm build:apps

      - name: Check
        run: pnpm check
