name: Unit tests

on:
  pull_request:

jobs:
  tests:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check setup
        uses: ./.github/actions/check-setup

      - name: Run unit tests
        run: pnpm test:unit
